# -*- ruby -*-

require 'rubygems'
require 'hoe'

task :build do
  sh "cd ext && ruby extconf.rb && make"
end

task :test => :build

Hoe.new('circulardb', '1.0.0') do |p|
  p.summary = "CircularDB Ruby Bindings"
  p.author  = "Dan Sully"
  p.email   = "daniel-github@electricrain.com"
  p.spec_extras = {:extensions => ['ext/extconf.rb']}
end

# vim: syntax=ruby
