# -*- ruby -*-

require 'rubygems'
require 'power_hoe'

PowerHoe.new('circulardb') do |p|
  p.summary = "CircularDB Ruby Bindings"
  p.author  = "Dan Sully"
  p.email   = "dan@powerset.com"
  p.spec_extras = {:extensions => ['ext/extconf.rb']}
end

# vim: syntax=Ruby
